### PR TITLE
Add AVIF support

### PR DESCRIPTION
**Pull request by Pyroglyph**
This PR addresses #56.

Instead of erroring on input media with an unknown duration, we set it to zero and then treat all zero-length media as images.
There are currently some `unwrap`s that I'm not too happy about, but it "works on my machine™".

### CODE REVIEW

**Comment by alexheretic** [comment]
Thanks! I'll review once I'm back from holiday

**Comment by Pyroglyph** [comment]
> I've added some extension based image detection

It would be nice if there was some kind of list we could use that includes all image formats so we don't have to hardcode the extensions like we do currently.

> maybe just hint to try `-e libaom-av1`

Yes, that's what I was thinking of doing too. It's slower, but supports images with odd dimensions.

> vmaf doesn't seem to work well always [...] Could be because of the yuv conversion

I've done some quick experiments on my end and I can't quite pin down why it fails sometimes. I did find that converting both the reference and distorted images to `y4m` and feeding that into `ab-av1 vmaf` worked just fine though.

> I wonder if [vmaf wil] provide more meaningless scores for arbitrary resolution images

Yes, but only if comparing to other images of differing resolutions. It's stated [here](https://github.com/Netflix/vmaf/blob/master/resource/doc/faq.md#q-will-vmaf-work-on-4k-videos) that if you compare two videos of the same resolution with the wrong model (e.g. comparing 2x 4K videos with the 1080p model), it will still provide a good relative comparison, which is what we're using it for, right?

> The code is avif/av1 only

I might be misunderstanding, but I thought that was the point? Hence the name of the project.

> Duration=zero is screwing up the progress bar logic, perhaps this can be improved for image scenario?

FFmpeg doesn't seem to give any sort of indication as to how much of a given frame it's finished processing, so whenever we check the progress it's either going to be 0% or 100% since we're only working with 1 frame. It especially sucks with large images that take a longer time to process because you have absolutely no idea how long it's going to take.

**Comment by alexheretic** [comment]
> It would be nice if there was some kind of list we could use that includes all image formats so we don't have to hardcode the extensions like we do currently.

Though it would still be hardcoded just somewhere else ;) As long as we list all the formats that _don't_ always have zero duration then we should be ok, so it's probably good enough to get going.

> > vmaf doesn't seem to work well always [...] Could be because of the yuv conversion

> I've done some quick experiments on my end and I can't quite pin down why it fails sometimes. I did find that converting both the reference and distorted images to y4m and feeding that into ab-av1 vmaf worked just fine though.

I found it seems to work fine if I use yuv420p pixel format, whereas the 10bit one generally used as default has issues. I can set it to the former whenever images are used as a workaround [0068eca](https://github.com/alexheretic/ab-av1/pull/57/commits/0068eca23601ac505a00462ebf443e83c275acd6)

> > The code is avif/av1 only

> I might be misunderstanding, but I thought that was the point? Hence the name of the project.

True, though since v0.4 ab-av1 supports all ffmpeg video encoders. It's useful to compare to av1 using the same crf/vmaf search algorithm. It probably applies less to images or rather only to images that are really vcodec key frames. Maybe webp could work? But just supporting avif is probably ok to begin with.

> Duration=zero is screwing up the progress bar logic

One tweak is to avoid setting the bar length to zero (use at least 1) which should avoid the bars starting completed. [0068eca](https://github.com/alexheretic/ab-av1/pull/57/commits/0068eca23601ac505a00462ebf443e83c275acd6)

The final encode, in auto-encode, is also technically unnecessary since we already did it during the crf-search. This is also true of short videos, but they are not particularly common so I never optimised it. It might be worth optimising now though, or maybe just for images if that's simpler.

**Comment by alexheretic** [comment]
>The final encode, in auto-encode, is also technically unnecessary since we already did it during the crf-search. This is also true of short videos, but they are not particularly common so I never optimised it. It might be worth optimising now though, or maybe just for images if that's simpler.

I think we can raise a ticket for this to look at later + the "use libaom-av1" hint. In which case I think this PR is ready to merge. Any blockers from your side @Pyroglyph?

**Comment by alexheretic** [comment]
On the other hand using ImageMagick `convert pic.jpg pic.avif` seems fairly fast, compresses well and gets **100** vmaf scores. So "magick" indeed! I wonder if crf/video encoding techniques can really compete with this?

**Comment by alexheretic** [comment]
> On the other hand using ImageMagick convert pic.jpg pic.avif seems fairly fast, compresses well and gets 100 vmaf scores. So "magick" indeed! I wonder if crf/video encoding techniques can really compete with this?

Or rather ImageMagick converted avifs are getting great VMAF scores, but when I actually compress down to VMAF ~95 they look terrible whereas the vcodec encoded ones at ~95 look great :confused: I guess an example of VMAF not really working for images well?

**Comment by alexheretic** [comment]
Interestingly converting to `-pix_fmt yuv422p` seems to fix the ImageMagick scores without affecting the vcodec avif scores... I'm not sure why :thinking: 

But perhaps yuv422p for image vmaf is a better default then.

**Comment by alexheretic** [comment]
> But perhaps yuv422p for image vmaf is a better default then.

Full yuv444p also works fine and should have no chroma compression issues, so I'll use that for images.

**Comment by alexheretic** [comment]
> Full yuv444p also works fine and should have no chroma compression issues, so I'll use that for images.

Actually it's simpler still to use yuv444p10le for all image & video vmaf, should work everywhere and take into account chroma compression.

**Comment by alexheretic** [comment]
Merged for the next release, thanks for your help @Pyroglyph !

**Pull request merged**
