### PR TITLE
vmaf: -r 24 & PTS-STARTPTS

### PR DESCRIPTION
**Pull request by alexheretic**
When calculating VMAF use 24 fps & setpts=PTS-STARTPTS. See https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md.

Relates to #108

### CODE REVIEW

**Comment by alexheretic** [comment]
Initial tests look good, I get identical results across a bunch of videos.

**Comment by iPaulis** [comment]
I'd say something is not right. I'm getting the same odd results as the previous build, and they do not match the results of ffmpeg.

Both builds, new and old one:
`ab-av1 vmaf --vmaf pool=harmonic_mean --reference '"I:\test\00100 (cap11)-011.mkv"' --distorted '"I:\test\00100 (cap11)-011.av1_hb.mkv"'`
VMAF score: 80.34283

Same files in ffmpeg:
`ffmpeg.exe -hide_banner -nostdin -r 24 -i "I:\test\00100 (Cap11)-011.av1_hb.mkv" -r 24 -i "I:\test\00100 (cap11)-011.mkv" -lavfi '[0:v]setpts=PTS-STARTPTS[main];[1:v]setpts=PTS-STARTPTS[ref];[main][ref]libvmaf=eof_action=endall:n_threads=15:pool=Mean:model=version=vmaf_v0.6.1' -f null -`
VMAF score: 95.647760

**Comment by alexheretic** [comment]
Isn't one using a harmonic-mean the other a standard mean? Though I can't actually find the docs for the vmaf `pool` arg. Maybe just leave it out when comparing?

**Comment by iPaulis** [comment]
Yeah, sorry, I always forget to leave the pool arg out because it does not work anyway (I'll open a new issue for this), but I rerun it just in case.
`ab-av1 vmaf --reference '"I:\test\00100 (cap11)-011.mkv"' --distorted '"I:\test\00100 (cap11)-011.av1_hb.mkv"'`
VMAF score: 80.34283

The resolution of both distorted and reference are the same. It is true that the source file is yuv420p and the encoded one is yuv420p10le, but that shouldn't affect the score so negatively, in fact, 10 bit encodes are usually of higher quality than 8 bit encodes, so it does not explain the score impact.

As I was saying, there is something wrong in there if the result is the same as the previous build and with plain ffmpeg terminal command it does work. 
So maybe the `-r` argument is not being applied or I don't know, but the result should be mostly equal to ffmpeg and it is not.

**Comment by alexheretic** [comment]
It's interesting this change hasn't seemed to actually improve anything yet, though also not regress. Perhaps that we convert the reference and distorted into a same pixel-format yuv streams already deals with pts issues?

I don't think I'll merge this without any tangible benefit.

**Comment by iPaulis** [comment]
I don't notice any difference in this build, it is like nothing has changed, so the inconsistencies are still there.

However, it is not a PTS issue in this sample file I'm testing in.
As some people point out in the github issues I linked, not all these kind of inconsistencies need PTS-STARTPTS to be fixed, although it does not hurt, and some other files may need it to fix their inconsistencies. That is way the vmaf docs recommend it.

But the most important part is to always set the framerate with `-r` before each input, as indicated by the docs, and that is the part that does not seem to be applying in ab-av1.

As a clarifying example, regardless of PTS corrections, **default PTS without specifying `-r`**:
`ffmpeg.exe -hide_banner -nostdin -i "I:\test\00100 (Cap11)-011.av1_hb.mkv" -i "I:\test\00100 (cap11)-011.mkv" -lavfi 'libvmaf=eof_action=endall:n_threads=15:pool=Mean:model=version=vmaf_v0.6.1' -f null -`

or

`ffmpeg.exe -hide_banner -nostdin -i "I:\test\00100 (Cap11)-011.av1_hb.mkv" -i "I:\test\00100 (cap11)-011.mkv" -lavfi '[0:v]setpts=PTS[main];[1:v]setpts=PTS[ref];[main][ref]libvmaf=eof_action=endall:n_threads=15:pool=Mean:model=version=vmaf_v0.6.1' -f null`
Both result in the same VMAF score as default setpts is PTS, whether we explicitly set it or not: **79.030344**. The pixel format conversions of ab-av1 seems to give an slightly better score **80.34283**. Being the score so close, it seems that no other parameters are being applied.

**If we instead set PTS-STARTPTS** the score gets improved, but not quite there yet:
`ffmpeg.exe -hide_banner -nostdin -i "I:\test\00100 (Cap11)-011.av1_hb.mkv" -i "I:\test\00100 (cap11)-011.mkv" -lavfi '[0:v]setpts=PTS-STARTPTS[main];[1:v]setpts=PTS-STARTPTS[ref];[main][ref]libvmaf=eof_action=endall:n_threads=15:pool=Mean:model=version=vmaf_v0.6.1' -f null -`
**VMAF score: 88.919527**

All of those results are incorrect, because the most important part is missing, the `-r` parameter.

**Now with `-r 24`:**
`ffmpeg.exe -hide_banner -nostdin -r 24 -i "I:\test\00100 (Cap11)-011.av1_hb.mkv" -r 24 -i "I:\test\00100 (cap11)-011.mkv" -lavfi 'libvmaf=eof_action=endall:n_threads=15:pool=Mean:model=version=vmaf_v0.6.1' -f null -`
**VMAF score: 95.647760**

That is the correct final score, thanks to the `-r` parameter, and as you can see, regardless of the setpts setting in this particular case. I've also run it combining `-r 24` with `setpts=PTS` and `setpts=PTS-STARTPTS` as indicated by the official docs, all of them resulting in the same score for this file, which means this is the correct and most reliable score.

You may download my exact files from [here](https://fromsmash.com/VMAF-sample-files) to test it yourself. I've added the source sample and 2 encoded files with the exact same encoding parameters, one with handbrake and one with ab-av1, both show vmaf score issues, they should not be so low for CRF 17.
The link will expire in 24h. Please, see if you can reproduce my results.

All the tests above are with a handbrake encoded file, but to further reinforce the results I have also repeated every parameter combination with an ab-av1 encoded file, and the results were mostly the same with one exception.
- ab-av1's vmaf score was again mostly equal to the ffmpeg score without `-r 24 `nor `PTS-STARTPTS` parameters, in this case: **73.88504**, which is too low.
- The exception was that this time with ffmpeg and `PTS-STARTPTS` (but without `-r 24`) the score was very very close to the recommended ffmpeg command **with `-r 24` and `PTS-STARTPTS`, in this case: 95.729659**. This means that ab-av1's pixel format conversion does not deal with any of these PTS issues, while they do get fixed by `PTS-STARTPTS` for this file, and specially `-r 24` for every file.
-----------------------------------
With all this results we can logically conclude that: 
- Having in mind that both distorted files were encoded with the same parameters and crf17, they should have very similar vmaf scores, and they do with the ffmpeg recommended settings (95.647760 vs 95.729659), but not with ab-av1 (80.34283 vs 73.88504), so we can conclude that the correct score is the ffmpeg one, once the appropriate parameters are used as indicated by the vmaf docs.
- There could be something wrong with the implementation of `-r 24` and `setpts=PTS-STARTPTS` in ab-av1. As I have tested the parameters independently we know that nor one nor the other is being correctly applied, because ab-av1's vmaf scores remain the same while ffmpeg vmaf scores do get improved by each parameter.
Maybe you could debug by printing or logging how the final ffmpeg call looks like, and doublecheck that all parameters are there in the correct order and syntax. Ideally, I guess this would be the easiest option to fix.
- Some of the conversions that ab-av1 makes could be negating or invalidating these parameters somehow, which hurts the final result.
- Those pixel format conversion are in fact not helping fix these score inconsistencies.

Sorry for such a long post, but I was trying to be thorough with this issue, and I think the results speak for themselves and the conclusions are solid.

**Comment by alexheretic** [comment]
Thanks, I was wondering whether it would work better setting the rate & pts on the pixel-format converted yuv pipes before the vmaf invocation, but I didn't have any good test cases.

Now I have your examples, this does indeed seem to be the trick. 

```
$ ab-av1 vmaf --reference 00100\ \(cap11\)-011.mkv --distorted 00100\ \(cap11\)-011.av1_hb.mkv
95.64776
```

We are now using `-r 24 -i - -pix_fmt $best -vf setpts=PTS-STARTPTS -f yuv4mpegpipe` for both reference & distorted, then passing into the vmaf call.

Seems encouraging, I'll also run some most tests with this setup.

**Comment by alexheretic** [comment]
My small suite of test cases seem fine too :+1:

**Comment by iPaulis** [comment]
Yes, exactly, that was it, doing the process in this order fixes it.

I've also tested my small suite of samples with the new update and they are all good, scores make sense and match the ffmpeg ones with the recommended parameters.

Nice! 🙌

**Comment by alexheretic** [comment]
Great thanks for your help with this @iPaulis!

**Pull request merged**
